### PR TITLE
Newstructure

### PR DESCRIPTION
**Pull request by Nakamcode**
Restructured the list, and added framework subdirectories. up to date with the main repo

### CODE REVIEW

**Comment by Nakamcode** [comment]
My PR has a conflict, I'm working on it.

**Comment by ykdojo** [comment]
Any updates?

**Comment by Nakamcode** [comment]
please, can you brief me on why my PR is always having conflict? I worked on the conflict last week but it is back again now.

**Comment by Nakamcode** [comment]
Alright,  I will work on the conflict and also remove the HTML tags;

**Comment by ykdojo** [comment]
Looks like this has been inactive for a while, so I'll close it. Feel free to send a new PR in the future, though.

**Comment by Nakamcode** [comment]
I have been busy a little, I will try my best to make a PR  in the future

**Pull request closed without merging**
